name: gitaction_assignment

on: 
  push:
    branches: [master]

jobs:
  bulidtest:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        python_ver : [3.6,3.7]

    steps:
      - uses: actions/checkout@v3
      
      - name : installing_dependencis
        run: pip install -r requirements.txt

      - name: running app
        run: python src/calculate_area.py

      - name: testing app in ubantu
        if: runner.os == 'Linux'
        run: export PYTHONPATH=src
        



           
      
      
    

  
      
