name: gitaction_assignment

on: 
  push:
    branches: [master]

jobs:
  bulidtest:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        python_ver : [3.6,3.7]
    env:
      PYTHONPATH: "src"

    steps:
      - uses: actions/checkout@v3
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-pip-
      
      - name : installing_dependencis
        run: pip install -r requirements.txt

      - name: running app
        run: python src/calculate_area.py

      - name: testing app in ubantu
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Upload pytest coverage report to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pytest-coverage-report
          path: coverage.xml
      
      - name: Send failure email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Job status Notification
          body: The job ${{job.status}}!
          to: sharulhn43@gmail.com
          from: GitHub Actions
          secure: true
     


        



           
      
      
    

  
      
